### PR TITLE
chore: add docfx session to noxfile, normalize

### PR DESCRIPTION
**Pull request by tseaver**
Unbreaking the `docs-presubmit` build.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@tseaver Thanks, I think we should also run synthtool to have other changes, in order to see if the test is actually passing.

**Comment by tseaver** [comment]
@tmatsuo I lost my synthtool-fu during my hiatus.  Can I just get my local copy updated to current `master` and run?  Are there new OS-level dependencies?

**Comment by tmatsuo** [comment]
@tseaver Maybe I can add a commit to the branch.

For the record, I was told there is a dependency on bazel.

**Comment by tmatsuo** [comment]
I think you rebased, that should work too. Thanks!

**Comment by tseaver** [comment]
@tmatsuo I merged #99 to `master`, and then merged it here, which seems to be getting `docs-presubmit` to actually run.

**Comment by tmatsuo** [comment]
The docs-presubmit is passing :)

Do you know why the samples are failing?

**Comment by tmatsuo** [comment]
At a glance, the test has sth like `time.sleep(10)`, so they might be eventually consistent tests.

**Comment by tseaver** [comment]
@tmatsuo We are hitting quota issues, breaking snippets / systests / samples.

**Pull request merged**
