### PR TITLE
feat: expose read-only 'Instance.create_time' property

### PR DESCRIPTION
**Pull request by tseaver**
From new field in the 'Instance' proto, added in PR #449.

### CODE REVIEW

**Review by chrisrossi — APPROVED** [review]
LGTM

**Review by kolea2 — CHANGES_REQUESTED** [review]
Thanks for this! Please hold off on merging for now, need to confirm implementation across languages.

**Comment by tseaver** [comment]
@kolea2 
> Thanks for this! Please hold off on merging for now, need to confirm implementation across languages.

OK.  I've merged with `main` and fixed up the somewhat tricky conflicts (all in tests).

**Comment by Mariatta** [comment]
Closing as this is not planned work.

**Comment by Mariatta** [comment]
We can reopen if it's needed.

**Pull request closed without merging**
