### PR TITLE
chore: remove superseded owlbot replacements

### PR DESCRIPTION
**Pull request by tseaver**
Toward #416.

### CODE REVIEW

**Review by dandhlee — APPROVED** [review]

**Comment by tseaver** [comment]
PR needs an approval from somebody in @googleapis/python-samples-owners.

**Comment by tseaver** [comment]
Weird -- it certainly _looks_ like @dandhlee is a [member of @googleapis/python-samples-owners](https://github.com/orgs/googleapis/teams/python-samples-owners/members).

**Comment by tseaver** [comment]
OK, I'm guessing that approval from a member of @googleapis/api-bigtable is required?

**Comment by dandhlee** [comment]
It looks like api-bigtable team is needed.

**Comment by tseaver** [comment]
Summoning @crwilcox, @craiglabenz, @billyjacobson, @kolea2

**Pull request merged**
