### PR TITLE
docs: Fixed a typo in the readme

### PR DESCRIPTION
**Pull request by shweta345**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by Mariatta** [comment]
I think you need to amend your commit message and change it to start with `docs: ` 
See https://github.com/googleapis/python-bigtable/pull/758/checks?check_run_id=12265907486

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
@shweta345 can you please amend the commit message such that it uses conventional commit?
It should start with `docs: ` 
 https://github.com/googleapis/python-bigtable/pull/758/checks?check_run_id=12265907486

**Comment by shweta345** [comment]
@Mariatta Apologies I was figuring out the amend command :)

**Comment by Mariatta** [comment]
@shweta345 
On command line with this branch checked out, do `git commit --amend -m "your new commit message here"`

This tutorial might help https://www.atlassian.com/git/tutorials/rewriting-history

**Comment by Mariatta** [comment]
Then you need to push the change
Not sure of your set up, try 
```
git push
```

or you may need
```
git push origin
```

**Comment by shweta345** [comment]
@Mariatta Done with the push as well when I amended the commit message. I see that all the changes appear approved. I just wanted to know if there is anything else breaking that needs to be fixed.  I am using Git through Terminal on my Mac.

**Comment by Mariatta** [comment]
It doesn't look like the amended commit got pushed to this PR. We're still only seeing the commit where the commit message did not start with `docs:`.

Can you ensure that your local change gets pushed to this branch? (`shweta345:shweta345-fixtypo`) Perhaps it was pushed to a different branch. Or whether the `git push` command completed successfully?

**Comment by shweta345** [comment]
@Mariatta Finally resolved the issue and used VSCode for creating a new branch. https://github.com/googleapis/python-bigtable/pull/760. Thank you for all your help :)

**Pull request closed without merging**
