### PR TITLE
chore(samples): Fixed a typo in the readme

### PR DESCRIPTION
**Pull request by shweta345**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by dandhlee — DISMISSED** [review]
Thank you!

**Comment by dandhlee** [comment]
Ah. This has the same issue as #758.

On the commit message, it should just say `chore` rather than docs, as `docs` triggers a new release and sample updates don't need one.

Could you amend the commit message and push again? Don't need to create a new branch and a new PR, but if that helps then that works too.

**Comment by shweta345** [comment]
@dandhlee Noted. I edited the message. Can you let me know if it amended properly?

**Comment by dandhlee** [comment]
Can you amend and push? I still see it as `docs`: https://github.com/googleapis/python-bigtable/pull/760/commits

**Review by Mariatta — APPROVED** [review]

**Pull request merged**
